using Equibles.Web.Authentication;

namespace Equibles.Tests.Web;

public class AuthSettingsTests {
    [Fact]
    public void IsEnabled_WhenBothUsernameAndPasswordSet_ReturnsTrue() {
        var settings = new AuthSettings { Username = "admin", Password = "pass" };

        settings.IsEnabled.Should().BeTrue();
    }

    [Fact]
    public void IsEnabled_WhenUsernameIsNull_ReturnsFalse() {
        var settings = new AuthSettings { Username = null!, Password = "pass" };

        settings.IsEnabled.Should().BeFalse();
    }

    [Fact]
    public void IsEnabled_WhenUsernameIsEmpty_ReturnsFalse() {
        var settings = new AuthSettings { Username = "", Password = "pass" };

        settings.IsEnabled.Should().BeFalse();
    }

    [Fact]
    public void IsEnabled_WhenPasswordIsNull_ReturnsFalse() {
        var settings = new AuthSettings { Username = "admin", Password = null! };

        settings.IsEnabled.Should().BeFalse();
    }

    [Fact]
    public void IsEnabled_WhenPasswordIsEmpty_ReturnsFalse() {
        var settings = new AuthSettings { Username = "admin", Password = "" };

        settings.IsEnabled.Should().BeFalse();
    }

    [Fact]
    public void IsEnabled_WhenBothNull_ReturnsFalse() {
        var settings = new AuthSettings { Username = null!, Password = null! };

        settings.IsEnabled.Should().BeFalse();
    }

    [Fact]
    public void IsEnabled_WhenBothEmpty_ReturnsFalse() {
        var settings = new AuthSettings { Username = "", Password = "" };

        settings.IsEnabled.Should().BeFalse();
    }

    [Fact]
    public void SessionSecret_IsAutoGeneratedOnConstruction() {
        var settings = new AuthSettings();

        settings.SessionSecret.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void SessionSecret_IsValidBase64() {
        var settings = new AuthSettings();

        var act = () => Convert.FromBase64String(settings.SessionSecret);
        act.Should().NotThrow();
    }

    [Fact]
    public void SessionSecret_GeneratesDifferentValuesEachTime() {
        var settings1 = new AuthSettings();
        var settings2 = new AuthSettings();

        settings1.SessionSecret.Should().NotBe(settings2.SessionSecret);
    }
}
