<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Equibles.Core.AutoWiring" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.Core\Equibles.Core.csproj" />
    <ProjectReference Include="..\Equibles.CommonStocks.Repositories\Equibles.CommonStocks.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Messaging\Equibles.Messaging.csproj" />
  </ItemGroup>
</Project>
