// <auto-generated />
using System;
using System.Collections.Generic;
using Equibles.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Equibles.Migrations.Migrations
{
    [DbContext(typeof(EquiblesDbContext))]
    [Migration("20260329152921_AddCftcAndCboeModules")]
    partial class AddCftcAndCboeModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_search");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equibles.Cboe.Data.Models.CboePutCallRatio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CallVolume")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("PutCallRatio")
                        .HasColumnType("numeric");

                    b.Property<long?>("PutVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("RatioType")
                        .HasColumnType("integer");

                    b.Property<long?>("TotalVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RatioType", "Date")
                        .IsUnique();

                    b.ToTable("CboePutCallRatio");
                });

            modelBuilder.Entity("Equibles.Cboe.Data.Models.CboeVixDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("CboeVixDaily");
                });

            modelBuilder.Entity("Equibles.Cftc.Data.Models.CftcContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LatestReportDate")
                        .HasColumnType("date");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("CftcContract");
                });

            modelBuilder.Entity("Equibles.Cftc.Data.Models.CftcPositionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CftcContractId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ChangeCommLong")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeCommShort")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeNonCommLong")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeNonCommShort")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeOpenInterest")
                        .HasColumnType("bigint");

                    b.Property<long>("CommLong")
                        .HasColumnType("bigint");

                    b.Property<long>("CommShort")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NonCommLong")
                        .HasColumnType("bigint");

                    b.Property<long>("NonCommShort")
                        .HasColumnType("bigint");

                    b.Property<long>("NonCommSpreads")
                        .HasColumnType("bigint");

                    b.Property<long>("NonRptLong")
                        .HasColumnType("bigint");

                    b.Property<long>("NonRptShort")
                        .HasColumnType("bigint");

                    b.Property<long>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PctCommLong")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PctCommShort")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PctNonCommLong")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PctNonCommShort")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<long>("TotalRptLong")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRptShort")
                        .HasColumnType("bigint");

                    b.Property<int?>("TradersCommLong")
                        .HasColumnType("integer");

                    b.Property<int?>("TradersCommShort")
                        .HasColumnType("integer");

                    b.Property<int?>("TradersNonCommLong")
                        .HasColumnType("integer");

                    b.Property<int?>("TradersNonCommShort")
                        .HasColumnType("integer");

                    b.Property<int?>("TradersTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate");

                    b.HasIndex("CftcContractId", "ReportDate")
                        .IsUnique();

                    b.ToTable("CftcPositionReport");
                });

            modelBuilder.Entity("Equibles.CommonStocks.Data.Models.CommonStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cik")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Cusip")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("IndustryId")
                        .HasColumnType("uuid");

                    b.Property<double>("MarketCapitalization")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<List<string>>("SecondaryTickers")
                        .HasColumnType("text[]");

                    b.Property<long>("SharesOutStanding")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Cik")
                        .IsUnique();

                    b.HasIndex("Cusip");

                    b.HasIndex("IndustryId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("CommonStock");
                });

            modelBuilder.Entity("Equibles.CommonStocks.Data.Models.Taxonomies.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Industry");
                });

            modelBuilder.Entity("Equibles.Congress.Data.Models.CongressMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CongressMember");
                });

            modelBuilder.Entity("Equibles.Congress.Data.Models.CongressionalTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountFrom")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountTo")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CongressMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilingDate");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("CommonStockId", "TransactionDate");

                    b.HasIndex("CongressMemberId", "TransactionDate");

                    b.HasIndex("CommonStockId", "CongressMemberId", "TransactionDate", "TransactionType", "AssetName")
                        .IsUnique();

                    b.ToTable("CongressionalTrade");
                });

            modelBuilder.Entity("Equibles.Errors.Data.Models.Error", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RequestSummary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Seen")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.HasIndex("Seen");

                    b.HasIndex("Source");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("Equibles.Finra.Data.Models.DailyShortVolume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Market")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("ShortExemptVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("ShortVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CommonStockId", "Date")
                        .IsUnique();

                    b.ToTable("DailyShortVolume");
                });

            modelBuilder.Entity("Equibles.Finra.Data.Models.ShortInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AverageDailyVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangeInShortPosition")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentShortPosition")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("DaysToCover")
                        .HasColumnType("numeric");

                    b.Property<long>("PreviousShortPosition")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SettlementDate");

                    b.HasIndex("CommonStockId", "SettlementDate")
                        .IsUnique();

                    b.ToTable("ShortInterest");
                });

            modelBuilder.Entity("Equibles.Fred.Data.Models.FredObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("FredSeriesId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FredSeriesId", "Date")
                        .IsUnique();

                    b.ToTable("FredObservation");
                });

            modelBuilder.Entity("Equibles.Fred.Data.Models.FredSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequency")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ObservationEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ObservationStart")
                        .HasColumnType("date");

                    b.Property<string>("SeasonalAdjustment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Units")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("SeriesId")
                        .IsUnique();

                    b.ToTable("FredSeries");
                });

            modelBuilder.Entity("Equibles.Holdings.Data.Models.InstitutionalHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cik")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CrdNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Form13FFileNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StateOrCountry")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Cik")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("InstitutionalHolder");
                });

            modelBuilder.Entity("Equibles.Holdings.Data.Models.InstitutionalHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cusip")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateOnly>("FilingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InstitutionalHolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvestmentDiscretion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAmendment")
                        .HasColumnType("boolean");

                    b.Property<int?>("OptionType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<int>("ShareType")
                        .HasColumnType("integer");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<string>("TitleOfClass")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.Property<bool>("ValuePending")
                        .HasColumnType("boolean");

                    b.Property<long>("VotingAuthNone")
                        .HasColumnType("bigint");

                    b.Property<long>("VotingAuthShared")
                        .HasColumnType("bigint");

                    b.Property<long>("VotingAuthSole")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber");

                    b.HasIndex("FilingDate");

                    b.HasIndex("ReportDate");

                    b.HasIndex("CommonStockId", "ReportDate");

                    b.HasIndex("InstitutionalHolderId", "ReportDate");

                    b.HasIndex("CommonStockId", "InstitutionalHolderId", "ReportDate", "ShareType", "OptionType")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CommonStockId", "InstitutionalHolderId", "ReportDate", "ShareType", "OptionType"), false);

                    b.ToTable("InstitutionalHolding");
                });

            modelBuilder.Entity("Equibles.InsiderTrading.Data.Models.InsiderOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDirector")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTenPercentOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OfficerTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerCik")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StateOrCountry")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerCik")
                        .IsUnique();

                    b.ToTable("InsiderOwner");
                });

            modelBuilder.Entity("Equibles.InsiderTrading.Data.Models.InsiderTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AcquiredDisposed")
                        .HasColumnType("integer");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FilingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InsiderOwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAmendment")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnershipNature")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerShare")
                        .HasColumnType("numeric");

                    b.Property<string>("SecurityTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SharesOwnedAfter")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionCode")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber");

                    b.HasIndex("FilingDate");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("CommonStockId", "TransactionDate");

                    b.HasIndex("InsiderOwnerId", "TransactionDate");

                    b.HasIndex("CommonStockId", "InsiderOwnerId", "TransactionDate", "TransactionCode", "SecurityTitle")
                        .IsUnique();

                    b.ToTable("InsiderTransaction");
                });

            modelBuilder.Entity("Equibles.Media.Data.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Extension")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("File");

                    b.HasDiscriminator<string>("Discriminator").HasValue("File");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Equibles.Media.Data.Models.FileContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("bytea");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("FileContent");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Chunks.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<int>("EndPosition")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartLineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StartPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType");

                    b.HasIndex("DocumentId", "Index")
                        .IsUnique();

                    b.HasIndex("Id", "Content", "DocumentType", "DocumentId", "Ticker", "ReportingDate")
                        .HasAnnotation("Npgsql:StorageParameter:key_field", "Id");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Id", "Content", "DocumentType", "DocumentId", "Ticker", "ReportingDate"), "bm25");

                    b.ToTable("Chunk");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Chunks.Embedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Vector>("Vector")
                        .HasColumnType("vector");

                    b.Property<int>("VectorDimension")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId", "Model")
                        .IsUnique();

                    b.ToTable("Embedding");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReportingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReportingForDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ReportingDate");

                    b.HasIndex("ReportingForDate");

                    b.HasIndex("CommonStockId", "DocumentType");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.FailToDeliver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SettlementDate");

                    b.HasIndex("CommonStockId", "SettlementDate")
                        .IsUnique();

                    b.ToTable("FailToDeliver");
                });

            modelBuilder.Entity("Equibles.Yahoo.Data.Models.DailyStockPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustedClose")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("CommonStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CommonStockId", "Date")
                        .IsUnique();

                    b.ToTable("DailyStockPrice");
                });

            modelBuilder.Entity("Equibles.Media.Data.Models.Image", b =>
                {
                    b.HasBaseType("Equibles.Media.Data.Models.File");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("Equibles.Cftc.Data.Models.CftcPositionReport", b =>
                {
                    b.HasOne("Equibles.Cftc.Data.Models.CftcContract", "CftcContract")
                        .WithMany("Reports")
                        .HasForeignKey("CftcContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CftcContract");
                });

            modelBuilder.Entity("Equibles.CommonStocks.Data.Models.CommonStock", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.Taxonomies.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Equibles.Congress.Data.Models.CongressionalTrade", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equibles.Congress.Data.Models.CongressMember", "CongressMember")
                        .WithMany("Trades")
                        .HasForeignKey("CongressMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");

                    b.Navigation("CongressMember");
                });

            modelBuilder.Entity("Equibles.Finra.Data.Models.DailyShortVolume", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");
                });

            modelBuilder.Entity("Equibles.Finra.Data.Models.ShortInterest", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");
                });

            modelBuilder.Entity("Equibles.Fred.Data.Models.FredObservation", b =>
                {
                    b.HasOne("Equibles.Fred.Data.Models.FredSeries", "FredSeries")
                        .WithMany("Observations")
                        .HasForeignKey("FredSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FredSeries");
                });

            modelBuilder.Entity("Equibles.Holdings.Data.Models.InstitutionalHolding", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equibles.Holdings.Data.Models.InstitutionalHolder", "InstitutionalHolder")
                        .WithMany("Holdings")
                        .HasForeignKey("InstitutionalHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Equibles.Holdings.Data.Models.HoldingManagerEntry", "ManagerEntries", b1 =>
                        {
                            b1.Property<Guid>("InstitutionalHoldingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("InvestmentDiscretion")
                                .HasColumnType("integer");

                            b1.Property<string>("ManagerName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int?>("ManagerNumber")
                                .HasColumnType("integer");

                            b1.Property<long>("Shares")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint");

                            b1.HasKey("InstitutionalHoldingId", "Id");

                            b1.ToTable("HoldingManagerEntry");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionalHoldingId");
                        });

                    b.Navigation("CommonStock");

                    b.Navigation("InstitutionalHolder");

                    b.Navigation("ManagerEntries");
                });

            modelBuilder.Entity("Equibles.InsiderTrading.Data.Models.InsiderTransaction", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equibles.InsiderTrading.Data.Models.InsiderOwner", "InsiderOwner")
                        .WithMany("Transactions")
                        .HasForeignKey("InsiderOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");

                    b.Navigation("InsiderOwner");
                });

            modelBuilder.Entity("Equibles.Media.Data.Models.FileContent", b =>
                {
                    b.HasOne("Equibles.Media.Data.Models.File", "File")
                        .WithOne("FileContent")
                        .HasForeignKey("Equibles.Media.Data.Models.FileContent", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Chunks.Chunk", b =>
                {
                    b.HasOne("Equibles.Sec.Data.Models.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Chunks.Embedding", b =>
                {
                    b.HasOne("Equibles.Sec.Data.Models.Chunks.Chunk", "Chunk")
                        .WithMany("Embeddings")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Document", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equibles.Media.Data.Models.File", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.FailToDeliver", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");
                });

            modelBuilder.Entity("Equibles.Yahoo.Data.Models.DailyStockPrice", b =>
                {
                    b.HasOne("Equibles.CommonStocks.Data.Models.CommonStock", "CommonStock")
                        .WithMany()
                        .HasForeignKey("CommonStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonStock");
                });

            modelBuilder.Entity("Equibles.Cftc.Data.Models.CftcContract", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Equibles.Congress.Data.Models.CongressMember", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Equibles.Fred.Data.Models.FredSeries", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Equibles.Holdings.Data.Models.InstitutionalHolder", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("Equibles.InsiderTrading.Data.Models.InsiderOwner", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Equibles.Media.Data.Models.File", b =>
                {
                    b.Navigation("FileContent");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Chunks.Chunk", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("Equibles.Sec.Data.Models.Document", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
