<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
    <InternalsVisibleTo Include="Equibles.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlackwellSystems.Gcf" />
    <PackageReference Include="ModelContextProtocol" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.CommonStocks.Data\Equibles.CommonStocks.Data.csproj" />
  </ItemGroup>
</Project>
